#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

if env["vulkan"]:
    env.add_source_files(env.editor_sources, "shader_baker_export_plugin_platform_vulkan.cpp")

if env["d3d12"]:
    env.add_source_files(env.editor_sources, "shader_baker_export_plugin_platform_d3d12.cpp")

if env["metal"]:
    env.add_source_files(env.editor_sources, "shader_baker_export_plugin_platform_metal.cpp")

if env["webgpu"] and env.editor_build:
    env.add_source_files(env.editor_sources, "shader_baker_export_plugin_platform_webgpu.cpp")
    env.add_source_files(env.editor_sources, "webgpu_spec_constant_baker_export_plugin.cpp")
    env.add_source_files(env.editor_sources, "webgpu_shader_capture_editor_plugin.cpp")
    env.add_source_files(env.editor_sources, "webgpu_spec_constant_debugger_plugin.cpp")
